[package]
name = "devy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pandoc = "0.8.11"
pandoc_ast = "0.8.6"
pest = "2.7.9"
pest_derive = "2.7.9"
